#' Plot Estimates by Choice
#'
#' Visualizes the variance of estimates conditional on a selected
#' discrete and continous choice.
#'
#' @param df The data frame as generated by \code{exhaust_design()}.
#' @param est A character value to indicate the variable in \code{df} that contains the pont estimate
#'   that you want to plot.
#' @param lb A character value indicating the variable in \code{df} that contains
#'   the lower bound of the estimate.
#' @param ub A character value indicating the variable in \code{df} that contains
#'   the upper bound of the estimate.
#' @param dchoice A character value to indicate the discrete choice that you want to partition
#'   your estimates on.
#' @param cchoice A character value to indicate the continous choice for the coloring of the
#'   point ranges.
#' @param width The \code{width} parameter for \code{\link[ggplot2]{position_dodge2}}
#'   to spread out the point ranges within the discrete choice area.
#' @return A \code{ggplot} object containing the plot.
#' @details See the vignette of the package for further details on how to implement the RDF workflow.
#' @examples
#' \dontrun{
#'   print("Sorry. No examples yet.")
#' }
#' @export

plot_rdf_estimates_by_choice <- function(df, est, lb, ub,
                                         dchoice, cchoice = NULL,
                                         width = 1) {
  df <- df %>%
    dplyr::arrange_(dchoice, est)

  if(!is.null(cchoice)) {
    ggplot2::ggplot(df, ggplot2::aes_string(x = dchoice,
                                            group = dchoice,
                                            color = cchoice)) +
      ggplot2::geom_pointrange(ggplot2::aes_string(y = est, ymin = lb, ymax = ub),
                               position = ggplot2::position_dodge2(width = width)) +
      ggplot2::theme_minimal() +
      ggplot2::xlab(sprintf("Discrete Choice: %s", dchoice)) +
      ggplot2::ylab("Estimate and confidence interval")
  } else {
    ggplot2::ggplot(df, ggplot2::aes_string(x = dchoice, group = dchoice)) +
      ggplot2::geom_pointrange(ggplot2::aes_string(y = est, ymin = lb, ymax = ub),
                               position = ggplot2::position_dodge2(width = width)) +
      ggplot2::theme_minimal() +
      ggplot2::xlab(sprintf("Discrete Choice: %s", dchoice)) +
      ggplot2::ylab("Estimate and confidence interval")
  }
}
