#' Plot Estimate Ridge Lines by Discrete Choice
#'
#' Visualizes the variance of an estimate conditional on a selected discrete choice.
#'
#' @param df The data frame as generated by \code{exhaust_design()}.
#' @param est A character value to indicate the variable in \code{df} that contains the pont estimate
#'   that you want to plot.
#' @param dchoice A character value to indicate the discrete choice that you want to partition
#'   your estimate ridgelines on.
#' @param ... Additional parameters that are being passed on to \code{ggridges::geom_density_redges()}
#' @return A \code{ggplot} object containing the plot.
#' @details See the vignette of the package for further details on how to implement the RDF workflow.
#' @examples
#' \dontrun{
#'   print("Sorry. No examples yet.")
#' }
#' @export

plot_rdf_ridges_by_dchoice <- function(df, est, dchoice, ...) {
  ggplot2::ggplot(df, ggplot2::aes_string(x = est, y = dchoice,
                                          group = dchoice)) +
    ggridges::geom_density_ridges(...) +
    ggridges::theme_ridges()
}
